export const LOADED_SEARCHED_RECIPIES = 'LOADED_SEARCHED_RECIPIES';
export const LOADED_SELECTED_RECIPE = 'LOADED_SELECTED_RECIPE';
export const LOADING_DATA_FAILURE = 'LOADING_DATA_FAILURE';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';